export const tad = [
	'P.V. TOAR',
	'YENLY YOYANG',
	'JANUAR MOKOLINTAD',
	'REINALD BOGDADI',
	'TRISNO WIDODO',
	'SUHARDI MODEONG',
	'ARNOLD RUDI DALEGI',
	'YOUFIN LUASUSUN',
	'GERLY TUMBELAKA',
	'TIMOTHY LONGDONG',
	'JECKY PELE',
	'TENO YAMBO',
	'KRISKY WATUNG',
	'DESMON KARONGKONG',
	'RECKY LAKUNSING',
	'ARVI BRAYEN WOWILING'
];
